# Global settings
global_settings:
  seed: 12345
  project: MIM
  experiment: SimMIM-t1_flair-128_16 # enc-inpmods-inpsize_masksize
  root_dir: /projects/prjs1526/anyBrainer/experiments

# Logging settings
logging_settings:
  dev_mode: False
  worker_logs: False
  save_logs: True
  wandb_enable: True
  wandb_entity: petros-koutsouvelis-maastricht-university
  wandb_watch_enable: True
  wandb_watch_kwargs:
    log_freq: 5000
    log_graph: True
    log: 'all'

# Data settings
# NOTE: This config uses a different datamodule that enables explicit control
# over: (i) which modalities are used for each channel, and (ii) whether
# modalities/acquisitions should be unique or not; e.g., someone can
# use T1w-T1w for contrastive learning and should set distinct_modalities to False.
# Also allows for multiple modalities per channel and retrieves all possible pairs.
pl_datamodule_settings:
  name: MultimodalDataModule
  data_dir: /projects/prjs1526/data-pretraining/fomo-60k_clean
  data_handler_kwargs:
    data_format: GenericNifti
    exts: [".npy"]
  train_val_test_split: [0.95, 0.05, 0.0]
  num_workers: 12
  batch_size: 8
  extra_dataloader_kwargs:
    shuffle: True
    pin_memory: False
  train_transforms: 
    name: get_mim_transforms
    keys: ["ch1", "ch2"]
    input_size: 128
    mask_size: 16
    mask_ratio_shared: [0.4, 0.6] # same mask locations for all channels; input as a range
    mask_ratio_unique: [0.05, 0.15] # strictly unique mask locations for each channel
    random_offset: True # apply a random offset to the mask grid
    val_mode: False
  val_transforms: 
    name: get_mim_transforms
    keys: ["ch1", "ch2"]
    input_size: 128
    mask_size: 16
    mask_ratio_shared: [0.4, 0.6]
    mask_ratio_unique: [0.05, 0.15]
    random_offset: True
    val_mode: True
  test_transforms: 
    name: get_mim_transforms
    keys: ["ch1", "ch2"]
    input_size: 128
    mask_size: 16
    mask_ratio_shared: [0.4, 0.6]
    mask_ratio_unique: [0.05, 0.15]
    random_offset: True
    val_mode: True
  extra_kwargs:
    modalities_per_ch: 
      - ["t1"] # will look for t1.npy in the data directory -> `ch1` will contain this modality
      - ["flair"] # will look for flair.npy in the data directory -> `ch2` will contain this modality
    distinct_modalities: True
    distinct_acquisitions: True

# Model
# NOTE: The network `Multimodal3DSwinMIMFPN` is compatible with the `MultimodalDataModule`. 
# Particularly, it has a its own patch embedding block that separately encodes each channel. 
# This allows: (i) masking the tokens of each channel independently, and (ii) injecting
# (ii) modality-specific tokens for each channel (this requires using the `expected_modalities` 
# argument and the `MultimodalDataModule` datamodule for storing the modality name in the data
# dictionary).
# The model `MultimodalMIMModel` expects the data dict keys to already contain the mask
# and reconstruction targets for each channel, which is ensured by the `get_mim_transforms`
# used above.
  name: MultimodalMIMModel
  model_kwargs:
    name: Multimodal3DSwinMIMFPN
    in_channels: 2
    patch_size: 2
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 7
    embed_dim: 48
    use_v2: True
    extra_swin_kwargs:
      use_checkpoint: True
    use_vanilla_swin: True
    merge_mode: and
    inject_modality_tokens: False
    expected_modalities:
    fusion: none
    fpn_width: 32
  optimizer_kwargs:
    name: AdamW
    auto_no_weight_decay: True
    lr: 0.0001
    weight_decay: 0.01
  lr_scheduler_kwargs:
    name: CosineAnnealingWithWarmup
    interval: step
    frequency: 1
    warmup_iters: 10000
    total_iters: 200000
    eta_min: 0.001
  loss_fn_kwargs:
    name: SmoothL1Loss
    beta: 1.0
  artifacts_settings: # logs images of reconstructions for visual monitoring
    log_every_n_steps: 500
    log_max_n_items: 1

# Checkpoint settings
ckpt_settings:
  new_version: False
  model_checkpoint:
  save_every_n_steps: 25000
  save_top_k: -1
  save_last: True

# Callback settings (other than model checkpointing)
pl_callback_settings: []

# Trainer settings (pl.Trainer kwargs)
pl_trainer_settings:
  max_steps: 200000
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  precision: bf16-mixed
  devices: 2
  strategy: ddp_find_unused_parameters_true
  accelerator: auto
  profiler: simple
  num_nodes: 1
  log_every_n_steps: 100
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
  overfit_batches: 0.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  fast_dev_run: False